export const CARS = {
    DEMO_CAR: {
        imageSrc: "images/car-test.png",
        width: 53,
        height: 100,
        maxSpeed: 10,
        acceleration: 0.1,
        modelSrc: 'models/Koenigsegg.glb',
        price: 100,
        name: "Машина для краш-тестов"
    },
    BUGATTI: {
        imageSrc: "images/bugatti.png",
        width: 53,
        height: 100,
        maxSpeed: 8,
        acceleration: 2,
        modelSrc: 'models/old_rusty_car/scene.gltf',
        price: 200,
        name: "Бугагатти"
    },
    LADA: {
        imageSrc: "images/lada.png",
        width: 50,
        height: 100,
        maxSpeed: 4,
        acceleration: 0.01,
    },
    MINI_COOPER: {
        imageSrc: "images/minicooper.png",
        width: 50,
        height: 100,
        maxSpeed: 6,
        acceleration: 0.09,
    },
    CITY_JIP: {
        imageSrc: "images/cityjip.png",
        width: 50,
        height: 100,
        maxSpeed: 9,
        acceleration: 0.04,
    },
    OLD_ASTON_MARTIN: {
        imageSrc: "images/oldastonmartin.png",
        width: 50,
        height: 100,
        maxSpeed: 13,
        acceleration: 0.3,
    },
    NEW_ASTON_MARTIN: {
        imageSrc: "images/newastonmartin.png",
        width: 50,
        height: 100,
        maxSpeed: 15,
        acceleration: 0.6,
    },
    FERRARI: {
        imageSrc: "images/ferrari.png",
        width: 50,
        height: 100,
        maxSpeed: 20,
        acceleration: 0.1,
    },
    EIGHTBITCAR: {
        imageSrc: "images/8bitcar.png",
        width: 50,
        height: 90,
        maxSpeed: 8,
        acceleration: 0.8,
    },
    AUDIFEIGHT: {
        imageSrc: "images/audif8.png",
        width: 50,
        height: 100,
        maxSpeed: 24,
        acceleration: 1,
    },
    MOTOBIKE: {
        imageSrc: "images/moto.png",
        width: 50,
        height: 100,
        maxSpeed: 25,
        acceleration: 1.5,
    }
}